server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evita que el navegador cachee config.js entre despliegues distintos
    location = /config.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
